module.exports = {
  apps: [
    {
      name: "odds-redis",
      cwd: __dirname,
      script: "src/server.js",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      min_uptime: "10s",
      max_restarts: 5,
      restart_delay: 5000,
      max_memory_restart: "4G",
      node_args: "--max-old-space-size=3072",
      kill_timeout: 90000,
      time: true,
      env: {
        NODE_ENV: "production",
        UV_THREADPOOL_SIZE: "16",
        SOURCE_DB_CONNECTION_LIMIT: "16",
        PROVIDER_MAX_CONCURRENT: "32",
        PROVIDER_MAX_REQUESTS_PER_MINUTE: "800",
        PROVIDER_MIN_TIME_MS: "8",
        PROVIDER_SLOW_REQUEST_MS: "750",
        PROVIDER_P95_WARNING_MS: "500",
        PROVIDER_SLOW_CONSECUTIVE_COUNT: "3",
        PROVIDER_WARNING_COOLDOWN_MS: "60000",
        BALL_BY_BALL_DATA_AGE_WARNING_MS: "5000",
        MARKET_DB_WRITE_BATCH_SIZE: "500",
        MARKET_DISCOVERY_CONCURRENCY: "4",
        MARKET_SUBSCRIPTION_BATCH_SIZE: "50",
        RECONCILE_SUBSCRIPTIONS_ON_START: "false",
        PROVIDER_TICK_COALESCE_MS: "100",
        BALL_BY_BALL_LOG_TO_FILE: "false",
        LINE_MARKET_EVENT_BATCH_SIZE: "10",
        REDIS_MEMORY_CACHE_LIMIT: "50000",
        MARKET_DISCOVERY_CACHE_LIMIT: "50000",
        SCORE_HASH_CACHE_LIMIT: "50000",
      },
    },
    {
      name: "odds-public-api",
      cwd: __dirname,
      script: "src/publicApiServer.js",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      min_uptime: "10s",
      max_restarts: 5,
      restart_delay: 5000,
      max_memory_restart: "768M",
      node_args: "--max-old-space-size=512",
      kill_timeout: 15000,
      time: true,
      env: {
        NODE_ENV: "production",
        PUBLIC_API_PORT: "5674",
      },
    },
  ],
};
