module.exports = {
  apps: [{
    name: "odds-redis",
    cwd: __dirname,
    script: "src/server.js",
    instances: 1,
    exec_mode: "fork",
    autorestart: true,
    restart_delay: 5000,
    max_memory_restart: "12G",
    node_args: "--max-old-space-size=8192",
    kill_timeout: 90000,
    time: true,
    env: {
      NODE_ENV: "production",
      UV_THREADPOOL_SIZE: "32",
      SOURCE_DB_CONNECTION_LIMIT: "32",
      PROVIDER_MAX_CONCURRENT: "64",
      PROVIDER_MIN_TIME_MS: "4",
      MARKET_DB_WRITE_BATCH_SIZE: "1000",
      MARKET_SUBSCRIPTION_BATCH_SIZE: "100",
      PROVIDER_TICK_COALESCE_MS: "10",
      REDIS_MEMORY_CACHE_LIMIT: "200000",
      MARKET_DISCOVERY_CACHE_LIMIT: "200000",
      SCORE_HASH_CACHE_LIMIT: "200000",
      RESULT_BATCH_SIZE: "250",
      RESULT_MAX_CALLS_PER_RUN: "250",
      RESULT_MARKET_LIMIT: "10000",
    },
  }],
};
