const express = require("express");
const sourceMarkets = require("../controllers/sourceMarketController");

const router = express.Router();
router.get("/overview", sourceMarkets.overview);
router.get("/markets", sourceMarkets.list);
router.get("/fancies", sourceMarkets.listFancies);
router.get("/markets/discovery", sourceMarkets.marketDiscoveryStatus);
router.get("/competitions", sourceMarkets.listCompetitions);
router.get("/competitions/sync", sourceMarkets.competitionSyncStatus);
router.post("/competitions/sync", sourceMarkets.runCompetitionSync);
router.get("/events", sourceMarkets.listEvents);
router.get("/events/sync", sourceMarkets.eventSyncStatus);
router.post("/events/sync", sourceMarkets.runEventSync);
router.get("/sync", sourceMarkets.syncStatus);
router.post("/sync", sourceMarkets.runSync);
router.get("/results/sync", sourceMarkets.resultSyncStatus);
router.post("/results/sync", sourceMarkets.runResultSync);
router.get("/results", sourceMarkets.listResults);
router.post("/subscribe", sourceMarkets.subscribeManual);
router.post("/unsubscribe-all", sourceMarkets.unsubscribeAllMarkets);
router.post("/events/:eventId/unsubscribe", sourceMarkets.unsubscribeEvent);
module.exports = router;
